# Generated by Django 2.2 on 2019-05-07 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cadet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xnum', models.CharField(max_length=6)),
                ('phoneNum', models.IntegerField()),
                ('classYear', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carMake', models.CharField(max_length=20)),
                ('carModel', models.CharField(max_length=30)),
                ('carColor', models.CharField(max_length=20)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hitch.Cadet')),
            ],
        ),
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departureTime', models.DateTimeField()),
                ('seatsAvailable', models.IntegerField()),
                ('storageAvailable', models.CharField(max_length=30)),
                ('departureLocation', models.CharField(max_length=30)),
                ('comments', models.CharField(blank=True, max_length=100, null=True)),
                ('destination', models.ManyToManyField(to='hitch.Destination')),
                ('passengers', models.ManyToManyField(to='hitch.Cadet')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hitch.Vehicle')),
            ],
        ),
    ]
